---
- name: Retrieve all manifest to install
  find:
    paths: "{{ kubectl_apply_basedir}}/manifests"
    file_type: "directory"
  register: find_manifest
  delegate_to: 127.0.0.1
  connection: local
  run_once: True
  tags:
    - kubectl_apply


- name: List of all directory to be deployed
  ansible.builtin.debug:
    var: "find_manifest.files|map(attribute='path')"
  tags:
    - kubectl_apply
  

- name: Loop on playbook manifest to perform include_vars
  include_vars:
    file: "{{ item }}/vars"
  delegate_to: 127.0.0.1
  connection: local
  run_once: True
  with_items: 
    - "{{ find_manifest.files | map(attribute='path')  }}"
  tags:
    - kubectl_apply

- name: Loop on playbook manifest to perform action
  delegate_to: 127.0.0.1
  connection: local
  run_once: True
  vars:
   - kube_deploy_action: "{{ item.split('/')[-1] | lower}}_deploy_action"
  with_items: 
    "{{ find_manifest.files | map(attribute='path')  }}"
  command: "kubectl {{ lookup('vars', kube_deploy_action) }} -f {{ item }}"
  tags:
    - kubectl_apply